name: Deployment

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: git pull
        run: | 
           cd /home/AzureAdmin/python/PythonProject
           sudo git pull
